### ISSUE TITLE
The animated cards just don't work 

### ISSUE THREAD

**Issue by Hello9001** [Foocett/CardsForHumanity#14]
They will show a animation on the incorrect card and might even play on the card that you just played before the cards are flipped when you didn't even have the card with animation

**Comment by Hello9001** [comment]
Actually every card played animates to subway surfers for all players after some event that I haven't figured out

**Comment by Hello9001** [comment]
actually it always animates it like that even after nuking the game

**Comment by Foocett** [comment]
Fixed, I'm a little stupid
